### ISSUE TITLE
 The future of gornir.New() 

### ISSUE THREAD

**Issue by nleiva** [nornir-automation/gornir#24]
Should `gornir.New()` provide safe defaults?. Should require you to provide mandatory attributes?. Today looks as simple as:

```go
func New() *Gornir {
	return new(Gornir)
}
```

**Comment by dbarrosop** [comment]
I think everything should provide sane defaults, problem is that there are no sane defaults at this point. I also don't think `gornir.New()` is the place to provide sane defaults, instead, each plugin should handle its own sane defaults and `gornir.New` construct a valid Gornir object. For instance:

``` golang
inv, err := inventory.NewSomeRESTInventory(url, optsForNSOT...)
if err != nil {
   // handle err
}
logger := logger.NewSomeLogger(address, optsForES...)
if err != nil {
   // handle err
}
rnr := runner.Parallel(optsParallel...)

gr := gornir.New(logger, inv, rnr)
```

So each plugin handles its own defaults and optional builders (I am thinking the pattern you originally proposed for gornir would be great for the plugins) while gornir is just what glues everything together.

**Comment by dbarrosop** [comment]
Later on we could also implement complex "initializers" that abstracts the pattern above (as another form of plugin?). For instance, nornir has the same pattern as described above (ish) but then there is an initializer `InitNornir` that takes a configuration file in YAML format and does all the magic for you. For instance:

``` yaml
---
core:
    num_workers: 20
inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "advanced_filtering/inventory/hosts.yaml"
        group_file: "advanced_filtering/inventory/groups.yaml"
```
